# Generated by Django 5.0.4 on 2024-08-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
